<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Ajouter un citoyen</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <h1>Ajouter un citoyen</h1>
  <form action="addPerson.php" method="post" id="addPersonForm">
    <label for="nom">Nom</label>
    <input type="text" id="nom" name="nom" required><br><br>
    
<label for="prenom">Prénom</label>
<input type="text" id="prenom" name="prenom" required><br><br>

<label for="dateNaissance">Date de naissance</label>
<input type="date" id="dateNaissance" name="dateNaissance" required><br><br>

<label for="numeroTelephone">Numéro de téléphone (555-XXXX)</label>
<input type="tel" id="numeroTelephone" name="numeroTelephone" pattern="555-[0-9]{4}" required><br><br>

<label for="taille">Taille</label>
<input type="number" id="taille" name="taille" maxlength="3" minlength="3"><br><br>

<label for="examPsycho">Examen Psychologique</label>
<select id="examPsycho" name="examPsycho" required>
  <option value="1">Validé</option>
  <option value="0">Non Validé</option>
</select><br><br>

<input type="submit" value="Ajouter">
  </form>
</body>
</html>