<html>
  <head>
  <meta charset="utf-8" />
    <title>Modifier un citoyen</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <h1>Modifier une personne</h1>
    <form action="updatePerson.php" method="post">
      <label for="person_list">Sélectionnez un citoyen</label>
      <?php
$pdo = new PDO("sqlite:FACDB.db");
$stmt = $pdo->query("SELECT * FROM Personne");
$personnes = $stmt->fetchAll();

echo "<select>";
foreach ($personnes as $personne) {
    echo "<option value='" . $personne['Identifiant'] . "'>" . $personne['Nom'] . " " . $personne['Prenom'] . "</option>";
}
echo "</select>";
?>
  <br>
  <br>
  <form action="updatePersonne.php" method="post">
    <label for="nom">Nom</label>
    <input type="text" id="nom" name="nom" required><br><br>
    
<label for="prenom">Prénom</label>
<input type="text" id="prenom" name="prenom" required><br><br>

<label for="dateNaissance">Date de naissance</label>
<input type="date" id="dateNaissance" name="dateNaissance" required><br><br>

<label for="numeroTelephone">Numéro de téléphone</label>
<input type="tel" id="numeroTelephone" name="numeroTelephone" required><br><br>

<label for="taille">Taille</label>
<input type="number" id="taille" name="taille"><br><br>

<label for="examPsycho">Examen Psychologique</label>
<select id="examPsycho" name="examPsycho" required>
  <option value="1">Validé</option>
  <option value="0">Non Validé</option>
</select><br><br>

<input type="submit" value="Modifier">
  </form>
</form>
</body>
<script>
    function updateForm() {
  // Récupération de l'identifiant de la personne sélectionnée
  var selectedId = document.getElementById("person_list").value;

  // Requête pour récupérer les données de la personne sélectionnée
  var xhr = new XMLHttpRequest();
  xhr.open("GET", "get_person.php?id=" + selectedId, true);
  xhr.onreadystatechange = function() {
    if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {
      // Récupération des données de la personne
      var personData = JSON.parse(this.responseText);

      // Mise à jour des champs du formulaire avec les données de la personne
      document.getElementById("nom").value = personData.Nom;
      document.getElementById("prenom").value = personData.Prenom;
      document.getElementById("dateNaissance").value = personData.DateNaissance;
      document.getElementById("numeroTelephone").value = personData.NumeroTelephone;
      document.getElementById("taille").value = personData.Taille;
      document.getElementById("examPsycho").value = personData.ExamPsycho;
    }
  };
  xhr.send();
}
</script>
</html>